# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-10 09:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20160410_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 4, 10, 9, 40, 16, 544143, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
